use_default_settings:
  engines:
    remove:
      - ahmia
      - torch
      - wikidata

general:
  debug: false
  instance_name: "Ch00chKA Search"

search:
  safe_search: 1
  formats:
    - json

server:
  limiter: false
  image_proxy: false
